set -x AIDER_DARK_MODE True

set -x AIDER_USER_INPUT_COLOR #D3C6AA
set -x AIDER_TOOL_OUTPUT_COLOR #7A8478
set -x AIDER_TOOL_ERROR_COLOR #E67E80
set -x AIDER_TOOL_WARNING_COLOR #DBBC7F
set -x AIDER_ASSISTANT_OUTPUT_COLOR #7FBBB3
set -x AIDER_COMPLETION_MENU_COLOR #83C092
set -x AIDER_COMPLETION_MENU_BG_COLOR #2E383C
set -x AIDER_COMPLETION_MENU_CURRENT_COLOR #83C092
set -x AIDER_COMPLETION_MENU_CURRENT_BG_COLOR #2E383C

fish_add_path /opt/homebrew/bin
