alias ld="lazydocker"
alias dkl="docker logs -f"
alias dke="docker exec"
alias dkc="docker-compose"
alias dkcl="docker-compose logs"
alias dkcu="docker-compose up -d"
alias dkcd="docker-compose down"
alias dkcub="docker-compose up -d --build"
alias dkcb="docker-compose build"

alias dllobby="docker logs -f lobby"
alias delobby="docker exec -i lobby rcon-cli"
alias dlnijisaba="docker logs -f nijisaba"
alias denijisaba="docker exec -i nijisaba rcon-cli"
alias dlsubworld="docker logs -f subworld"
alias desubworld="docker exec -i subworld rcon-cli"
alias dlvelocity="docker logs -f velocity"
