alias gs='git status'
alias gfa='git fetch --all'
alias gpa='git pull --all'
alias gco="git checkout"
alias gcob="git checkout -b"
alias gsu='git stash save -u'
alias gsl='git stash list'
alias gsc='git stash clear'
alias gb='git branch --all'
alias gbl='git branch'
alias gbr='git branch --remote'
